-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 13:43:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cidade` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cidade` (
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `aeroporto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`voo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`voo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`voo` (
  `id_trecho` INT NOT NULL AUTO_INCREMENT,
  `origem` VARCHAR(45) NOT NULL,
  `destino` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_trecho`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aeroporto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aeroporto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aeroporto` (
  `id_aeroporto` INT NOT NULL AUTO_INCREMENT,
  `id_cidade` INT NOT NULL,
  `id_trecho` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id_aeroporto`),
  INDEX `fk_aeroporto_cidade_idx` (`id_cidade` ASC) VISIBLE,
  INDEX `fk_aeroporto_voo1_idx` (`id_trecho` ASC) VISIBLE,
  CONSTRAINT `fk_aeroporto_cidade`
    FOREIGN KEY (`id_cidade`)
    REFERENCES `mydb`.`cidade` (`id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aeroporto_voo1`
    FOREIGN KEY (`id_trecho`)
    REFERENCES `mydb`.`voo` (`id_trecho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`passageiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`passageiro` ;

CREATE TABLE IF NOT EXISTS `mydb`.`passageiro` (
  `id_passageiro` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT NOT NULL,
  PRIMARY KEY (`id_passageiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aviao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aviao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aviao` (
  `id_aviao` INT NOT NULL AUTO_INCREMENT,
  `capacidade` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_aviao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reserva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `id_passageiro` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_reserva`),
  INDEX `fk_reserva_passageiro1_idx` (`id_passageiro` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_passageiro1`
    FOREIGN KEY (`id_passageiro`)
    REFERENCES `mydb`.`passageiro` (`id_passageiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trecho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`trecho` ;

CREATE TABLE IF NOT EXISTS `mydb`.`trecho` (
  `id_voo` INT NOT NULL,
  `id_aviao` INT NOT NULL,
  `id_reserva` INT NOT NULL,
  `classe` INT NOT NULL,
  `assento` VARCHAR(45) NOT NULL,
  INDEX `fk_voo_has_aviao_aviao1_idx` (`id_aviao` ASC) VISIBLE,
  INDEX `fk_voo_has_aviao_voo1_idx` (`id_voo` ASC) VISIBLE,
  INDEX `fk_trecho_reserva1_idx` (`id_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_voo_has_aviao_voo1`
    FOREIGN KEY (`id_voo`)
    REFERENCES `mydb`.`voo` (`id_trecho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voo_has_aviao_aviao1`
    FOREIGN KEY (`id_aviao`)
    REFERENCES `mydb`.`aviao` (`id_aviao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trecho_reserva1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `mydb`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
